---
# Go Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
  labels:
    app: todo-backend
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
        version: v1
    spec:
      containers:
      - name: backend
        image: todo-backend:latest
        imagePullPolicy: Never  # Use local image only
        ports:
        - containerPort: 8083
          name: http
        env:
        - name: SERVER_PORT
          value: "8083"
        - name: SERVER_HOST
          value: "0.0.0.0"
        - name: GO_ENV
          value: "production"
        - name: GIN_MODE
          value: "release"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "300m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8083
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8083
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        # Security context
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL

---
# Go Backend Service  
apiVersion: v1
kind: Service
metadata:
  name: todo-backend-service
  labels:
    app: todo-backend
spec:
  type: ClusterIP  # Internal service only
  ports:
  - port: 8083
    targetPort: 8083
    protocol: TCP
    name: http
  selector:
    app: todo-backend

---
# ConfigMap for backend configuration (optional)
apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-backend-config
  labels:
    app: todo-backend
data:
  PORT: "8083"
  GO_ENV: "production"
  LOG_LEVEL: "info" 